import { getPost } from "../lib/blog-posts";
import { Article, articleMeta } from "../components/marketing/Article";
import { appStoreUrl } from "../components/marketing/MarketingChrome";

const post = getPost("turn-instagram-comments-into-sales");

export const meta = () => articleMeta(post);

const FAQS = [
  {
    q: "What is comment-to-DM automation?",
    a: "Comment-to-DM automation automatically sends a private direct message to anyone who comments on one of your Instagram posts. Instead of replying publicly in the comment thread, the app moves the conversation to DMs, where it can share a personalized message and a checkout link for the product featured in the post.",
  },
  {
    q: "How do I track sales from Instagram comments?",
    a: "Use a tool that sends uniquely tracked checkout links in its comment-to-DM replies. SocialReplAI generates a tracked Shopify checkout link for each conversation, so when the customer buys, the order is attributed back to the specific comment that started it. Your analytics show revenue split by DM-initiated versus comment-initiated conversations.",
  },
  {
    q: "Can Instagram comment replies include checkout links?",
    a: "Not useful ones — links in public comments are not clickable on Instagram. That is exactly why comment-to-DM exists: the automated private reply can carry a clickable, tracked Shopify checkout link, while the public thread stays clean.",
  },
  {
    q: "Does comment-to-DM work on every Instagram post?",
    a: "It works on posts from an Instagram Business or Creator account connected through Meta's API. In SocialReplAI you can enable or disable automation per post, and map each post to the Shopify product it features so the AI sends the right checkout link.",
  },
];

export default function CommentsIntoSales() {
  return (
    <Article post={post} faqs={FAQS}>
      <h2>The problem: comments are intent you can't cash in publicly</h2>
      <p>
        When someone comments "price?", "is this still available?", or "need
        this 😍" on your Instagram post, they are telling you they want to
        buy. But the comment thread is a dead end for commerce: links in
        Instagram comments are not clickable, public replies get buried, and
        answering "check your DMs!" manually does not scale past a handful of
        comments a day. Most Shopify stores simply leave this revenue on the
        table — the intent is there, but there is no path from comment to
        checkout.
      </p>

      <h2>The fix: comment-to-DM automation</h2>
      <p>
        Comment-to-DM automation watches your posts and, when someone
        comments, automatically sends that person a private DM. Because the
        reply lands in DMs instead of the public thread, it can include a
        clickable, tracked Shopify checkout link — something a public comment
        reply can never do. With SocialReplAI, the DM is generated by AI in
        your brand voice and references the product featured in the post the
        person commented on, so it reads like a helpful reply from the brand
        rather than a canned blast.
      </p>

      <h2>Why private replies convert better than public ones</h2>
      <p>
        Three reasons. First, clickability: the DM carries a working checkout
        link, while a public reply cannot. Second, attention: a DM creates a
        notification and a one-to-one thread, while a public reply competes
        with every other comment. Third, conversation: once the customer is in
        DMs, they can ask follow-up questions — "does it come in black?",
        "how long is shipping?" — and an AI agent can answer each one and keep
        guiding them toward checkout. A public thread ends after one reply; a
        DM thread ends at a purchase.
      </p>

      <h2>How to set it up on a Shopify store</h2>
      <p>
        Install{" "}
        <a
          href={appStoreUrl("blog_comments_to_sales_guide")}
          target="_blank"
          rel="noopener noreferrer"
        >
          SocialReplAI
        </a>{" "}
        from the Shopify App Store and connect your Instagram Business
        account. Then map your Instagram posts to the Shopify products they
        feature using the app's visual post grid — pick the product for each
        post, and toggle automation on for the posts you want covered. When
        someone comments on a mapped post, the app sends a private reply with
        an AI-written message and a checkout link for that exact product and
        variant. Posts you have not mapped fall back to smart product
        detection, where the AI infers the product from the conversation.
      </p>

      <h2>Attribution: know which comments made you money</h2>
      <p>
        The difference between "we automated comments" and "comments are now a
        sales channel" is attribution. Every checkout link SocialReplAI sends
        is uniquely tracked, so when a customer completes their order, the
        revenue is attributed back to the originating comment. The analytics
        dashboard splits attributed revenue by source — DM-initiated versus
        comment-initiated — and shows per-post performance on the Pro plan, so
        you can see which posts actually drive orders and post more of what
        works.
      </p>

      <h2>Practical tips for higher conversion</h2>
      <p>
        A few patterns consistently lift comment-to-DM conversion. Use
        comment-bait honestly: a caption like "comment SIZE and we'll DM you
        the details" sets the expectation that a DM is coming, which raises
        open rates. Keep the automated DM short — one or two sentences plus
        the link. Make sure your brand voice settings match your captions, so
        the DM feels continuous with the post. And leave follow-up enabled if
        you are on a plan that supports it: a single, polite follow-up message
        to customers who clicked but did not buy recovers checkouts that would
        otherwise be lost.
      </p>
    </Article>
  );
}
